/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refundsysteminsaudiairline;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author macbook
 */
public class cash_banking extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();
    DefaultListModel model2 = new DefaultListModel();
    Cash_and_Banking obj = new Cash_and_Banking();
    static String x11;
    static String x22;
    close close_obj = new close();

    /**
     * This method will return the list that contain the files.
     *
     * @return JList
     */
    public JList<String> getCashFile_display() {
        return cashFile_display;
    }

    /**
     * This method will return the ticket number.
     *
     * @return String return the ticket number
     */
    public String getTickNum() {
        return x22;
    }

    /**
     * Set new value for in x22.
     *
     * @param TickNum The new value .
     */

    public void setTickNum(String TickNum) {
        this.x22 = TickNum;
    }

    /**
     * Set new value for in x11.
     *
     * @param num The new value .
     */

    public void setNum(String num) {
        this.x11 = num;
    }

    /**
     * This method will return the file number.
     *
     * @return String return the file number
     */
    public String getNum() {
        return x11;
    }

    /**
     * Creates new form cash_banking
     */
    public cash_banking() {
        initComponents();
        setLocationRelativeTo(null);
        boolean flag1 = false;
        try {
            obj.storeInFile();
            String x = "";
            for (int i = 0; i < obj.getCash_array().length; i++) {

                for (int j = 0; j < obj.getCash_array()[i].length; j++) {
                    if (obj.getCash_array()[i][j] != null) {
                        flag1 = true;
                        x = "File " + (i + 1);

                    }

                }
                if (flag1 == true) {
                    model.addElement(x);
                    flag1 = false;
                }

            }

            cashFile_display.setModel(model);
            //////////////////////////////////////////////////////////////       
            obj.storeCreditCard();
            String x2 = "";
            for (int i = 0; i < obj.getCreditArray().length; i++) {

                if (obj.getCreditArray()[i] != null) {
                    x2 = "Ticket " + obj.getCreditArray()[i].getCustomer().getTicketNum();

                    model2.addElement(x2);
                }

            }
            cc_dispaly.setModel(model2);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(cash_banking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        undo_cash = new javax.swing.JLabel();
        undo_cash_msg = new javax.swing.JLabel();
        Suecces1 = new javax.swing.JLabel();
        Suecces = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cash = new javax.swing.JLabel();
        fail1 = new javax.swing.JLabel();
        undo_cc = new javax.swing.JLabel();
        undo_cc_msg = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cashFile_display = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        cc_dispaly = new javax.swing.JList<>();
        filenum = new javax.swing.JTextField();
        TickNum = new javax.swing.JTextField();
        send = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        language4 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        undo_cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undo_cashMouseClicked(evt);
            }
        });

        undo_cash_msg.setForeground(new java.awt.Color(255, 255, 255));
        undo_cash_msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undo_cash_msgMouseClicked(evt);
            }
        });

        Suecces1.setForeground(new java.awt.Color(143, 242, 173));

        Suecces.setForeground(new java.awt.Color(143, 242, 173));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Help");
        jLabel3.setToolTipText("Help");

        cash.setForeground(new java.awt.Color(255, 255, 255));
        cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashMouseClicked(evt);
            }
        });

        fail1.setForeground(new java.awt.Color(242, 143, 143));

        undo_cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undo_ccMouseClicked(evt);
            }
        });

        undo_cc_msg.setForeground(new java.awt.Color(255, 255, 255));
        undo_cc_msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undo_cc_msgMouseClicked(evt);
            }
        });

        fail.setForeground(new java.awt.Color(242, 143, 143));

        jScrollPane2.setViewportView(cashFile_display);

        jScrollPane1.setViewportView(cc_dispaly);

        filenum.setBackground(java.awt.Color.darkGray);
        filenum.setForeground(new java.awt.Color(255, 255, 255));
        filenum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        filenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenumActionPerformed(evt);
            }
        });

        TickNum.setBackground(java.awt.Color.darkGray);
        TickNum.setForeground(new java.awt.Color(255, 255, 255));
        TickNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        TickNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TickNumActionPerformed(evt);
            }
        });

        send.setForeground(new java.awt.Color(255, 255, 255));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ticket Number");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("File Number");

        language4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                language4MouseClicked(evt);
            }
        });

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Images/send.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(620, 620, 620)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(undo_cc_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(filenum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(undo_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Suecces, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel14))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(820, 820, 820)
                .addComponent(jLabel15))
            .addGroup(layout.createSequentialGroup()
                .addGap(960, 960, 960)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(820, 820, 820)
                .addComponent(fail1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1040, 1040, 1040)
                .addComponent(undo_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(TickNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1030, 1030, 1030)
                .addComponent(language4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(820, 820, 820)
                .addComponent(Suecces1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(840, 840, 840)
                .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1000, 1000, 1000)
                .addComponent(undo_cash_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(570, 570, 570)
                .addComponent(undo_cc_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(filenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(undo_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(Suecces, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel14))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel15))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(660, 660, 660)
                .addComponent(fail1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(660, 660, 660)
                .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(undo_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(TickNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(language4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(Suecces1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(undo_cash_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void language4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_language4MouseClicked
        Language lan_obj = new Language();

        lan_obj.setVisible(true);
    }//GEN-LAST:event_language4MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Main_page_operation main_obj = new Main_page_operation();
        setVisible(false);
        main_obj.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Main_page_login login_obj = new Main_page_login();
        setVisible(false);
        login_obj.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void TickNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TickNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TickNumActionPerformed

    private void filenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenumActionPerformed

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
       /// cc
       
       
        x22 = TickNum.getText();
        String ticNum = getTickNum();

        ImageIcon x = new ImageIcon("Screen Shot 2020-11-27 at 9.57.23 PM.png");

//        model2.remove(obj.getIndex_cc());
        int approve = JOptionPane.showConfirmDialog(null, "Are you sure you want to send ticket Number " + x22 + "? ", " ", JOptionPane.OK_CANCEL_OPTION);

        if (approve == 0) {
            fail.setText("");
            model2.remove(obj.getIndex_cc());
            undo_cc_msg.setText("");
            Suecces.setText("The Ticket " + x22 + " have transferred successfully to the Bank.");
            undo_cc.setIcon(x);
            undo_cc.setVisible(true);

        } else {
            
            Suecces.setText("");
            undo_cc_msg.setText("");
            fail.setText("The Ticket " + x22 + " did not transferred to the Bank.");
            undo_cc.setVisible(false);
        }
    }//GEN-LAST:event_sendMouseClicked

    private void cashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashMouseClicked
        x11 = filenum.getText();
        
        ImageIcon x = new ImageIcon("Screen Shot 2020-11-27 at 9.57.23 PM.png");

        int approve = JOptionPane.showConfirmDialog(null, "Are you sure you want to send ticket Number " + x11 + "? ", " ", JOptionPane.OK_CANCEL_OPTION);

        if (approve == 0) {
            fail1.setText("");
            model.remove(obj.getIndex_cash());
            undo_cash_msg.setText("");
            Suecces1.setText("The Ticket " + x11 + " have transferred successfully to the Bank.");
            undo_cash.setIcon(x);
             undo_cash.setVisible(true);

        } else {
            Suecces1.setText("");
            undo_cash_msg.setText("");
            fail1.setText("The Ticket " + x11 + " did not transferred to the Bank.");
             undo_cash.setVisible(false);
        }
    }//GEN-LAST:event_cashMouseClicked

    private void undo_ccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undo_ccMouseClicked
        Suecces.setText("");
        fail.setText("");
        undo_cc_msg.setText("The Ticket " + x22 + " have been Undo it's transferring.");
    }//GEN-LAST:event_undo_ccMouseClicked

    private void undo_cc_msgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undo_cc_msgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_undo_cc_msgMouseClicked

    private void undo_cashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undo_cashMouseClicked
        Suecces1.setText("");
        fail1.setText("");
        undo_cash_msg.setText("The Ticket " + x11 + " have been Undo it's approving.");
    }//GEN-LAST:event_undo_cashMouseClicked

    private void undo_cash_msgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undo_cash_msgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_undo_cash_msgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cash_banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cash_banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cash_banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cash_banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cash_banking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Suecces;
    private javax.swing.JLabel Suecces1;
    private javax.swing.JTextField TickNum;
    private javax.swing.JLabel cash;
    private javax.swing.JList<String> cashFile_display;
    private javax.swing.JList<String> cc_dispaly;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel fail1;
    private javax.swing.JTextField filenum;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel language4;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel send;
    private javax.swing.JLabel undo_cash;
    private javax.swing.JLabel undo_cash_msg;
    private javax.swing.JLabel undo_cc;
    private javax.swing.JLabel undo_cc_msg;
    // End of variables declaration//GEN-END:variables
}
