/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refundsysteminsaudiairline;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static refundsysteminsaudiairline.Close_complicated.ticketState;

/**
 *
 * @author macbook
 */
public class Close_simple extends javax.swing.JFrame {

    close close_obj = new close();
    RefundDepartment refundObj = new RefundDepartment();
    boolean check_calculate;
    boolean check_state;

    static double RefundedAmount;
    static String ticketState;

    File output = new File("Claimes.txt");

    File output_temp = new File("temp.txt");

    PrintWriter pen_temp;
    PrintWriter pen_claim;

    /**
     * Creates new form Close_simple
     */
    public Close_simple() {
        initComponents();
        setLocationRelativeTo(null);
        TickNum.setText(close_obj.getTicketNumber());
    }

    public void info(String pricee) {
        TicketPrice.setText(pricee);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        language1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back_button = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        undo1 = new javax.swing.JLabel();
        statesBox = new javax.swing.JCheckBox();
        TickNum = new javax.swing.JLabel();
        calculate = new javax.swing.JCheckBox();
        TicketPrice = new javax.swing.JLabel();
        undo = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        Suecces = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        language1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                language1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Help");
        jLabel3.setToolTipText("Help");

        Back_button.setForeground(new java.awt.Color(143, 242, 173));
        Back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_buttonMouseClicked(evt);
            }
        });

        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        undo1.setForeground(new java.awt.Color(255, 255, 255));

        statesBox.setForeground(new java.awt.Color(255, 255, 255));
        statesBox.setText("Turn to 'R'");

        TickNum.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        TickNum.setForeground(new java.awt.Color(255, 255, 255));

        calculate.setForeground(new java.awt.Color(255, 255, 255));
        calculate.setText("Calculate ");

        TicketPrice.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        TicketPrice.setForeground(new java.awt.Color(255, 255, 255));

        undo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoMouseClicked(evt);
            }
        });

        fail.setForeground(new java.awt.Color(236, 118, 118));

        Suecces.setForeground(new java.awt.Color(143, 242, 173));

        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Simple");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Images/s&c.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(620, 620, 620)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(language1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(TickNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(780, 780, 780)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1040, 1040, 1040)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(calculate)
                .addGap(116, 116, 116)
                .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(statesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(Back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1000, 1000, 1000)
                .addComponent(undo1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1040, 1040, 1040)
                .addComponent(undo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(980, 980, 980)
                .addComponent(Suecces, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(language1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(TickNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculate)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(statesBox))
                    .addComponent(Back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(undo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(undo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(Suecces, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        try {
            ImageIcon x = new ImageIcon("Screen Shot 2020-11-27 at 8.28.39 PM.png");
            ImageIcon y = new ImageIcon("Screen Shot 2020-11-27 at 9.57.23 PM.png");
            check_calculate = calculate.isSelected();
            check_state = statesBox.isSelected();

            ticketState = refundObj.turnStateIntoR_auto(check_state);

            if (check_calculate == true) {
                RefundedAmount = refundObj.calculateAuto();
            }
            if (ticketState.equalsIgnoreCase("R")) {
                ticketState = "R";
            } else {
                ticketState = "Open";
            }

            if (check_calculate == true || ticketState.equalsIgnoreCase("R")) {
                int save = JOptionPane.showConfirmDialog(null, "Are you sure to save your change on ticket Number " + close_obj.getTicketNumber() + "? ", " ", JOptionPane.OK_CANCEL_OPTION);
                if (save == 0) {
                    undo1.setText("");
                    fail.setText(" ");
                    Suecces.setText("Your work have\n"
                            + " been saved. ");

                    Back_button.setIcon(x);
                    undo.setIcon(y);
                    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
                    pen_temp = new PrintWriter(output_temp);

                    Scanner read = new Scanner(output); //read
                    String[] line;
                    while (read.hasNext()) {
                        line = read.nextLine().split(" ");

                        for (int i = 0; i < line.length; i++) {
                            if (close_obj.getTicketNumber().equalsIgnoreCase(line[1])) {
                                for (int j = 0; j <= 5; j++) {
                                    pen_temp.print(line[j] + " ");
                                }

                                pen_temp.print(ticketState + " ");
                                pen_temp.print(RefundedAmount + " ");
                                break;

                            } else {

                                pen_temp.print(line[i] + " ");

                            }

                        }
                        pen_temp.println("");
                    }
                    pen_temp.flush();
                    pen_temp.close();
                    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                    pen_claim = new PrintWriter(output);
                    Scanner read_temp = new Scanner(output_temp); //read

                    String[] line_temp;
                    while (read_temp.hasNext()) {
                        line_temp = read_temp.nextLine().split(" ");

                        for (int i = 0; i < line_temp.length; i++) {
                            pen_claim.write(line_temp[i] + " ");

                        }
                        pen_claim.write("\n");

                    }

                    pen_claim.flush();
                    pen_claim.close();
                } else {
                    undo1.setText("");
                    Suecces.setText(" ");
                    fail.setText("Your work did not\n"
                            + " been saved. ");

                }

            } else {
                undo1.setText("");
                Suecces.setText(" ");
                fail.setText("You did not change anything!");

            }
        } catch (IOException ex) {
            Logger.getLogger(Close_simple.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Main_page_login login_obj = new Main_page_login();
        setVisible(false);
        login_obj.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Main_page_operation main_obj = new Main_page_operation();
        setVisible(false);
        main_obj.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        close close_obj = new close();
        setVisible(false);
        close_obj.setVisible(true);
    }//GEN-LAST:event_cancelMouseClicked

    private void language1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_language1MouseClicked
        Language lan_obj = new Language();

        lan_obj.setVisible(true);
    }//GEN-LAST:event_language1MouseClicked

    private void Back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_buttonMouseClicked

        close close_obj = new close();
        setVisible(false);
        close_obj.setVisible(true);

    }//GEN-LAST:event_Back_buttonMouseClicked

    private void undoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoMouseClicked
        int approve = JOptionPane.showConfirmDialog(null, "Are you sure you want to undo your work? ", " ", JOptionPane.OK_CANCEL_OPTION);
        if (approve == 0) {
            fail.setText("");
            Suecces.setText("");
            undo1.setText("The Ticket have been Undo.");

        }
    }//GEN-LAST:event_undoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Close_simple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Close_simple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Close_simple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Close_simple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Close_simple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back_button;
    private javax.swing.JLabel Suecces;
    private javax.swing.JLabel TickNum;
    private javax.swing.JLabel TicketPrice;
    private javax.swing.JCheckBox calculate;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel language1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel save;
    private javax.swing.JCheckBox statesBox;
    private javax.swing.JLabel undo;
    private javax.swing.JLabel undo1;
    // End of variables declaration//GEN-END:variables
}
