/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refundsysteminsaudiairline;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author macbook
 */
public class login extends javax.swing.JFrame {

    RefundSystemWebsiteWindow obj = new RefundSystemWebsiteWindow();
    close close_obj = new close();
    approve approv_obj = new approve();
    cash_banking CB_obj = new cash_banking();

    File redFile_emp = new File("Employee.txt");

    File output = new File("Claimes.txt");
    Scanner read;
    PrintWriter pen;
    static String[] arrayLine2;
    
    
    static int id;
    static String password;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        login.id = id;
    }

    public static String getPassword() {
        return password;
    }

    public static void setPassword(String password) {
        login.password = password;
    }

  
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iban_theRightWay7 = new javax.swing.JLabel();
        iban_theRightWay8 = new javax.swing.JLabel();
        iban_theRightWay9 = new javax.swing.JLabel();
        iban_theRightWay10 = new javax.swing.JLabel();
        iban_theRightWay6 = new javax.swing.JLabel();
        iban_theRightWay5 = new javax.swing.JLabel();
        iban_theRightWay4 = new javax.swing.JLabel();
        iban_theRightWay3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Verify_emp = new javax.swing.JLabel();
        Verify1 = new javax.swing.JLabel();
        password_emp = new javax.swing.JPasswordField();
        l_name = new javax.swing.JTextField();
        ticktNum = new javax.swing.JTextField();
        id_emp = new javax.swing.JTextField();
        home = new javax.swing.JLabel();
        language = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iban_theRightWay7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iban_theRightWay7.setForeground(new java.awt.Color(255, 51, 0));
        iban_theRightWay7.setText("*");

        iban_theRightWay8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iban_theRightWay8.setForeground(new java.awt.Color(255, 51, 0));
        iban_theRightWay8.setText("*");

        iban_theRightWay9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iban_theRightWay9.setForeground(new java.awt.Color(255, 51, 0));
        iban_theRightWay9.setText("*");

        iban_theRightWay10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        iban_theRightWay10.setForeground(new java.awt.Color(255, 255, 255));
        iban_theRightWay10.setText("Must Enter");

        iban_theRightWay6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iban_theRightWay6.setForeground(new java.awt.Color(255, 51, 0));
        iban_theRightWay6.setText("*");

        iban_theRightWay5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iban_theRightWay5.setForeground(new java.awt.Color(255, 51, 0));
        iban_theRightWay5.setText("*");

        iban_theRightWay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        iban_theRightWay4.setForeground(new java.awt.Color(255, 255, 255));
        iban_theRightWay4.setText("Must Enter");

        iban_theRightWay3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        iban_theRightWay3.setForeground(new java.awt.Color(255, 51, 0));
        iban_theRightWay3.setText("*");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Help");
        jLabel3.setToolTipText("Help");

        Verify_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Verify_empMouseClicked(evt);
            }
        });

        Verify1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Verify1MouseClicked(evt);
            }
        });

        password_emp.setBackground(java.awt.Color.darkGray);
        password_emp.setForeground(new java.awt.Color(255, 255, 255));
        password_emp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        password_emp.setMinimumSize(new java.awt.Dimension(1, 18));
        password_emp.setPreferredSize(new java.awt.Dimension(1, 18));

        l_name.setBackground(java.awt.Color.darkGray);
        l_name.setForeground(new java.awt.Color(153, 153, 153));
        l_name.setText("Only Letters");
        l_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        l_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_nameMouseClicked(evt);
            }
        });
        l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameActionPerformed(evt);
            }
        });

        ticktNum.setBackground(java.awt.Color.darkGray);
        ticktNum.setForeground(new java.awt.Color(153, 153, 153));
        ticktNum.setText("Only Numbers");
        ticktNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ticktNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticktNumMouseClicked(evt);
            }
        });
        ticktNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticktNumActionPerformed(evt);
            }
        });

        id_emp.setBackground(java.awt.Color.darkGray);
        id_emp.setForeground(new java.awt.Color(153, 153, 153));
        id_emp.setText("Only Numbers");
        id_emp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        id_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_empMouseClicked(evt);
            }
        });
        id_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_empActionPerformed(evt);
            }
        });

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        language.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Images/login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(820, 820, 820)
                .addComponent(id_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(870, 870, 870)
                .addComponent(Verify_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(iban_theRightWay8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(iban_theRightWay6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1040, 1040, 1040)
                .addComponent(iban_theRightWay10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1030, 1030, 1030)
                .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(ticktNum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(iban_theRightWay3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(iban_theRightWay4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(iban_theRightWay7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(iban_theRightWay5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(820, 820, 820)
                .addComponent(password_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Verify1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1020, 1020, 1020)
                .addComponent(iban_theRightWay9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(620, 620, 620)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420)
                .addComponent(id_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(Verify_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(iban_theRightWay8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(iban_theRightWay6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(iban_theRightWay10))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(ticktNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(iban_theRightWay3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(iban_theRightWay4))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(iban_theRightWay7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(iban_theRightWay5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(password_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(Verify1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(iban_theRightWay9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void languageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageMouseClicked
        Language lan_obj = new Language();

        lan_obj.setVisible(true);
    }//GEN-LAST:event_languageMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Main_page_login main_obj = new Main_page_login();
        setVisible(false);
        main_obj.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void id_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_empActionPerformed

    private void Verify1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verify1MouseClicked

        int num = Integer.parseInt(ticktNum.getText());
        String name = l_name.getText();

        try {

            Boolean x;
            x = obj.enter_verify(name, num, "Customer");

            if (x == true) {
 
                 setVisible(false);

            }

        } catch (FileNotFoundException | ParseException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Verify1MouseClicked

    private void Verify_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verify_empMouseClicked
Main_page_operation obj_operation = new Main_page_operation();
         id = Integer.parseInt(id_emp.getText());
         password = password_emp.getText();

        boolean flag1 = false;
        boolean flag2 = false;

        String[] line;
        try {

            Scanner rederemp_scan = new Scanner(redFile_emp);

            Boolean x;
            x = obj.enter_verify(password, id, "Employee");

            if (x == true) {

//                setVisible(false);

                while (rederemp_scan.hasNext()) {
                    line = rederemp_scan.nextLine().split(" ");
                     Boolean flag = false;

       

                    if (password.equalsIgnoreCase(line[0]) && id == Integer.parseInt(line[1])) {

                        if (flag == false) {
                            setVisible(false);
                            flag = true;
                        }
                        if (flag == true) {
                            obj_operation.setVisible(true);
                        }
                    }
                }

            }

        } catch (FileNotFoundException | ParseException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Verify_empMouseClicked

    private void ticktNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticktNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticktNumActionPerformed

    private void l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameActionPerformed

    private void ticktNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticktNumMouseClicked
        ticktNum.setText("");
    }//GEN-LAST:event_ticktNumMouseClicked

    private void l_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_nameMouseClicked
        // TODO add your handling code here:
        l_name.setText("");
    }//GEN-LAST:event_l_nameMouseClicked

    private void id_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_empMouseClicked
        id_emp.setText("");
    }//GEN-LAST:event_id_empMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Verify1;
    private javax.swing.JLabel Verify_emp;
    private javax.swing.JLabel home;
    private javax.swing.JLabel iban_theRightWay10;
    private javax.swing.JLabel iban_theRightWay3;
    private javax.swing.JLabel iban_theRightWay4;
    private javax.swing.JLabel iban_theRightWay5;
    private javax.swing.JLabel iban_theRightWay6;
    private javax.swing.JLabel iban_theRightWay7;
    private javax.swing.JLabel iban_theRightWay8;
    private javax.swing.JLabel iban_theRightWay9;
    private javax.swing.JTextField id_emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField l_name;
    private javax.swing.JLabel language;
    private javax.swing.JPasswordField password_emp;
    private javax.swing.JTextField ticktNum;
    // End of variables declaration//GEN-END:variables
}
