/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refundsysteminsaudiairline;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author macbook
 */
public class Main_page_operation extends javax.swing.JFrame {

    File redFile_emp = new File("Employee.txt");

    RefundSystemWebsiteWindow obj = new RefundSystemWebsiteWindow();
    close close_obj = new close();
    approve approv_obj = new approve();
    cash_banking CB_obj = new cash_banking();

    /**
     * Creates new form Main_page_operation
     */
    public Main_page_operation() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        operation = new javax.swing.JLabel();
        read = new javax.swing.JLabel();
        language = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        operation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operationMouseClicked(evt);
            }
        });

        read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readMouseClicked(evt);
            }
        });

        language.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Help");
        jLabel3.setToolTipText("Help");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Images/main page operation.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1030, 1030, 1030)
                .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(operation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(960, 960, 960)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(570, 570, 570)
                .addComponent(operation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        boolean flag = false;
        Main_page_login login_obj = new Main_page_login();

        if (flag == false) {
            setVisible(false);
            flag = true;
        }
        if (flag == true) {
            login_obj.setVisible(true);
            flag = false;
        }

    }//GEN-LAST:event_logoutMouseClicked

    private void readMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readMouseClicked
        readMore read_obj = new readMore();
        setVisible(false);
        read_obj.setVisible(true);

    }//GEN-LAST:event_readMouseClicked

    private void languageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageMouseClicked
        Language lan_obj = new Language();

        lan_obj.setVisible(true);
    }//GEN-LAST:event_languageMouseClicked

    private void operationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operationMouseClicked
        login obj22 = new login();

        int id = obj22.getId();
        String password = obj22.getPassword();

        boolean flag1 = false;
        boolean flag = false;

        String[] line;
        Scanner rederemp_scan;
        try {
            rederemp_scan = new Scanner(redFile_emp);

            Boolean x;
            x = obj.enter_verify(password, id, "Employee");
            if (x == true) {

//            setVisible(false);
                while (rederemp_scan.hasNext()) {
                    line = rederemp_scan.nextLine().split(" ");

                    if (password.equalsIgnoreCase(line[0]) && id == Integer.parseInt(line[1])) {

                        if (line[2].equalsIgnoreCase("close") && flag1 == false) {
                            flag1 = true;

                            if (flag == false) {
                                setVisible(false);
                                flag = true;
                            }
                            if (flag == true) {
                                close_obj.setVisible(true);
                                flag = false;
                            }

                            break;

                        }
                        if (line[2].equalsIgnoreCase("approve") && flag1 == false) {
                            flag1 = true;

                            if (flag == false) {
                                setVisible(false);
                                flag = true;
                            }
                            if (flag == true) {
                                approv_obj.setVisible(true);
                                flag = false;
                            }

                            break;

                        }
                        if (line[2].equalsIgnoreCase("cash&banking") && flag1 == false) {
                            flag1 = true;

                            if (flag == false) {
                                setVisible(false);
                                flag = true;
                            }
                            if (flag == true) {
                                CB_obj.setVisible(true);
                                flag = false;
                            }

                            break;

                        }
                    }
                }

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main_page_operation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Main_page_operation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_operationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page_operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page_operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page_operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page_operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page_operation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel language;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel operation;
    private javax.swing.JLabel read;
    // End of variables declaration//GEN-END:variables
}
